extraction:
  cpp:
    after_prepare: 
      - python report.py 92
  cobol:
    after_prepare: 
      - python report.py 92
  csharp:
    after_prepare: 
      - python report.py 92
  java:
    after_prepare: 
      - python report.py 92
  javascript:
    after_prepare: 
      - python report.py 92
  python:
    after_prepare: 
      - python report.py 92
